name: Build Debian loong64 live cd

permissions: write-all

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:
jobs:
  debian:
    name: Build loong64 iso image
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        variant:
          - kde
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up loong64 Debian container
        uses: maus007/docker-run-action-fork@5ddaad0f7eedd03f64e412b1931852bd3031b273
        with:
          image: ghcr.io/loong64/loongnix:25
          options: --cpus=4 --platform linux/loong64 --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            apt update; apt install sudo git fakeroot debootstrap debian-cd simple-cdd xorriso squashfs-tools mtools curl	libxml2-utils -y
            git config --global --add safe.directory /work
            export DEBIAN_FRONTEND=noninteractive
            curl -fsSL https://salsa.debian.org/-/project/100777/uploads/67ffd6906e0fd6ea39607917e8f78655/live-build_20251022_all.deb -o live-build.deb
            apt install -y ./live-build.deb
            rm live-build.deb
            curl -fsSL http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb -o debian-archive-keyring.deb
            apt install -y ./debian-archive-keyring.deb
            rm debian-archive-keyring.deb
            bash -i ./build.sh --variant ${{ matrix.variant }}
            
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debian loong64 live cd ${{ matrix.variant }}
          path: ${{ github.workspace }}/images/*.iso
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
