name: Build Debian loong64 live cd

permissions: write-all

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "59 12 * * *"
  workflow_dispatch:
jobs:
  debian:
    name: Build loong64 iso image
    runs-on: self-hosted
    container: 
      image: ghcr.io/loong64/debian:trixie
      options: --cpus=2 --platform linux/loong64 --privileged
    permissions: write-all
    strategy:
      matrix:
        variant:
          - kde
    steps:
      # - name: Maximize build space
      #   uses: easimon/maximize-build-space@master
      #   with:
      #     root-reserve-mb: 4096
      #     swap-size-mb: 2048
      #     remove-dotnet: 'true'
      #     remove-android: 'true'

      - name: Install Deps
        run: |
          sed -i 's/deb.debian.org/mirror.sjtu.edu.cn/g' /etc/apt/sources.list.d/debian.sources
          sed -i 's/https/http/g' /etc/apt/sources.list.d/debian.sources
          apt update; 
          apt install sudo git fakeroot debootstrap debian-cd simple-cdd xorriso squashfs-tools mtools curl jq -y
          git config --global --add safe.directory /work

          curl -fsSL https://salsa.debian.org/-/project/100777/uploads/67ffd6906e0fd6ea39607917e8f78655/live-build_20251022_all.deb -o live-build.deb
          apt install -y ./live-build.deb
          rm live-build.deb

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build
        run: |
          bash -i ./build.sh --variant ${{ matrix.variant }}
  
      # - name: Set up loong64 Debian container
      #   uses: addnab/docker-run-action@v3
      #   with:
      #     image: ghcr.io/loong64/debian:trixie
      #     options: --cpus=4 --platform linux/loong64 --privileged -v ${{ github.workspace }}:/work
      #     run: |
      #       cd /work
      #       export DEBIAN_FRONTEND=noninteractive
      #       apt update; 
      #       apt install sudo git fakeroot debootstrap debian-cd simple-cdd xorriso squashfs-tools mtools curl jq -y
      #       apt install qemu-user qemu-user-binfmt binfmt-support curl python3 -y
      #       git config --global --add safe.directory /work

      #       curl -fsSL https://salsa.debian.org/-/project/100777/uploads/67ffd6906e0fd6ea39607917e8f78655/live-build_20251022_all.deb -o live-build.deb
      #       apt install -y ./live-build.deb
      #       rm live-build.deb

      #       bash -i ./build.sh --variant ${{ matrix.variant }}
                 
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debian loong64 live cd ${{ matrix.variant }}
          path: ${{ github.workspace }}/images/*.iso
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
